spring:
    application:
        name: ecotopia
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true

server:
    port: 8080

security:
    admin-permission-name: ADMIN
    admin-users:
        - admin.bebebe
    permissions:
        ADMIN:
            - ADD_PRODUCT
            - EDIT_PRODUCT
            - GET_PRODUCT
            - DELETE_PRODUCT
            - GET_CARTS
        CUSTOMER:
            - GET_PRODUCTS
            - EDIT_PRODUCTS_IN_ORDER
            - EDIT_PRODUCTS_IN_CART
            - CART

rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

